# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fe0dfb46-1175-4c25-a4cc-cc5527359c90";
      fsType = "ext4";
    };

  fileSystems."/mnt/lima-cidata" =
    { device = "/dev/disk/by-uuid/2023-08-24-19-35-49-32";
      fsType = "iso9660";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E786-79EB";
      fsType = "vfat";
    };

  fileSystems."/Users/jkeifer2" =
    { device = "mount0";
      fsType = "9p";
    };

  fileSystems."/tmp/lima" =
    { device = "mount1";
      fsType = "9p";
    };

  swapDevices = [ ];

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.enp0s1.useDHCP = lib.mkDefault true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.05"; # Did you read the comment?

}
